name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Init
      run: git submodule update --init --recursive
    - name: Make
      run: make
    - name: Run
      run: make run
      
